google_analytics:
  enabled: false
  code: UA-XXXXXX-1
plugins:
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-paginate-v2
  - jekyll-titles-from-headings
schema: default
twittercard:
  enabled: false
  username: "@"
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""
opengraph:
  enabled: true
logo: /img/jkan.png
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: dataset_categories
    values:
      layout: category
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization
navigation:
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/
  - title: Categories
    url: /categories/
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/
  dataset_categories:
    output: true
    permalink: /categories/:path/
kramdown:
  input: GFM
hero_image: /img/homepage-hero.jpg
title: " Open-Data Portal der Stadt Flensburg"
jkan_theme: Default
greeting: " Willkommen auf dem Open-Data Portal der Stadt Flensburg"
exclude:
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - scripts/src
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - netlify
  - netlify.toml
  - .parcel-cache
  - docs
hypothesis:
  enabled: false
description: Rechtsgrundlage für den Betrieb des Open-Data-Portals ist das
  Gesetz über offene Daten der Träger der öffentlichen Verwaltung
  (Offene-Daten-Gesetz - ODaG) . Dort wird in §4 der Betrieb des
  Open-Data-Portals geregelt.
baseurl: ./
